<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Drive Companion Terms</title>
    <link rel="stylesheet" href="{{ elixir('css/app.css') }}">
</head>
<body>
<div class="container">
<p class="text-muted">Last Updated: October 10, 2016</p>
<h1 class="text-center">TERMS OF USE</h1>
<p>
    Welcome to Drive Companion, (the “Service”). These Terms of Use govern your use of the Service on our Web site at https://drive-companion.com, as well as any mobile sites, mobile applications, and other internet points of presence that we make available to you as part of the Service (collectively, the “Site”). “Service,” as used in these Terms of Use, means the Web-based services we make available to users.
    By using the Service, you accept these Terms of Use. If you do not agree with any of these Terms of Use, you may not use the Service. As used in these Terms of Use, “we,” “us” or “our” means Engagenie, Inc.
</p>
<ol>
    <li><strong>MODIFICATIONS.</strong> We reserve the right to modify these Terms of Use by posting an updated version on our Web site from time to time.</li>
    <li><strong>PRIVACY.</strong> Your use of the Service, and our use of any personal information and content you submit to the Service, is governed by our
        <a href="{{url('/privacy',null,True)}}">Privacy Policy</a>. The Privacy Policy also governs our collection and use of email addresses, names and school information from users. We encourage you to review our Privacy Policy to familiarize yourself with our privacy practices.</li>
    <li><strong>ELIGIBILITY.</strong> Though we have designed the Service to allow users to easily distribute and share Google Drive Documents, our Web-based Service is not intended for anyone 13 years of age or younger. By using the Service, you represent that you are at least 13 years of age. COPPA requires that online service providers obtain parental consent before they collect personally identifiable information online from children who are under 13. Therefore, we only collect personal information through the Service from a child under 13 where that student’s school, district, and/or teacher has agreed (via the terms described in the following paragraph) to obtain parental consent for that child to use the Service and disclose personal information to us, for the use and benefit of the learning environment. If you are a student under 13, please do not send any personal information about yourself to us if your school, district, and/or teacher has not obtained this prior consent from your parent or guardian, and please do not send any personal information other than what we request from you in connection with the Service. If we learn we have collected personal information from a student under 13 without parental consent being obtained by his or her school, district, and/or teacher, or if we learn a student under 13 has provided us personal information beyond what we request from him or her, we will delete that information as quickly as possible. If you believe that a student under 13 may have provided us personal information in violation of this paragraph, please contact us at
        <a href="mailto:privacy@engagenie.com.">privacy@engagenie.com</a>. If you are a school, district, or teacher, you represent and warrant that you are solely responsible for complying with COPPA, meaning that you must obtain advance written consent from all parents or guardians whose children under 13 will be accessing the Service. When obtaining consent, you must provide parents and guardians with our Privacy Policy. If you are a teacher, you represent and warrant that you have permission and authorization from your school and/or district to use the Service as part of your curriculum, and for purposes of COPPA compliance, you represent and warrant that you are entering into these Terms on behalf of your school and/or district.</li>
    <li><strong>USING THE SERVICE.</strong> The Service will create, copy and share Google Drive documents on your behalf. To use the Service, you must first create an account on our Site with a unique username and password. You are responsible for all use of the Service that occurs under your user account. To use the Service, an administrator on the Organization’s Google Apps Domain must grant the Service domain-wide authority to the Google Drive API Scope.</li>
    <li><strong>NO LIABILITY FOR YOUR MESSAGE CONTENT.</strong> We assume no liability whatsoever for the content of the resource you use at the Service. If you use the Service to present information that could allow someone to determine the location or identity of a child remove it from the platform. Notwithstanding the foregoing, we reserve the right to block any resource that we reasonably believe may subject us, our service providers or our users to liability.</li>
    <li><strong>FEES.</strong> To use the Service, an Organization must purchase Credits before it’s users can create Classes (Course Sections). 1 credit is used for every Class created with the Service. Credits are non-refundable and non-transferrable. When Credits are purchased, the Organization will be issued an invoice to be paid within 30 days. We reserve the right to suspend the Service in the event of overdue invoices on the Organization’s account.</li>
    <li><strong>YOUR CONTENT; LICENSE.</strong> As between you and us, you own all intellectual property rights in any text, graphical, video or other content you in the form of Google Drive Documents submit to or through our Service (“Your Content”). You hereby grant us a non-exclusive, transferable, sub licensable, fully paid, royalty-free, perpetual, irrevocable, worldwide license to use, to display online and in any present or future media, to create derivate works of, to allow downloads of and/or distribute any such file or content, and to modify Your Content in order to make the Service and its features available to you and other users. You agree that we may distribute, display, and make available Your Content in accordance with the description of our Service on our Site. You represent and warrant that you either own, or have all rights and permissions necessary to submit, Your Content for distribution to other users through our Service, including any text, links, images, and other media you include in Your Content.</li>
    <li><strong>YOUR OBLIGATIONS WHEN USING THE SERVICE.</strong> You agree not to:
        <ol>
            <li>falsify your identity in regards to your role or occupation as a Student or Teacher;</li>
            <li>“frame,” distribute, resell, or (except as expressly allowed in these Terms of Use) permit access to the Service by any third party;</li>
            <li>use any robot, spider, data gathering, scraping or extraction tool or similar mechanism to access or attempt to view or obtain data from our Service;</li>
            <li>include anything in Your Content that infringes or misappropriates the intellectual property rights or other proprietary rights of any third parties, including their rights of privacy and publicity;</li>
            <li>include in Your Content any material that is obscene, illegal, threatening, or defamatory, or that contains software viruses, commercial solicitations, political campaigning, or any other form of “spam”;</li>
            <li>interfere or attempt to interfere with the Service or any other user’s access to the Site;</li>
            <li>reverse engineer, attempt to gain unauthorized access to, or attempt to discover the underlying source code or structure of the Service (including any feature, widget or application made available through the Service);</li>
            <li>use resources through the Service from users who have not consented to share such resources;</li>
            <li>use the Service in violation of any applicable law; or</li>
            <li>violate any agreement with your wireless service provider in connection with using the Service.</li>
        </ol>
    </li>
    <li><strong>OUR INTELLECTUAL PROPERTY RIGHTS.</strong> Except for Your Content (and content posted by other users), all text, graphics, logos, icons, and other content on the Service is the property of Engagenie, Inc., and protected by United States and international copyright laws. The technology we use to provide the Service, including without limitation software code or executables that we may make available to you in connection with using the Service, is exclusive property.</li>
    <li><strong>LINKS TO THIRD PARTY SITES.</strong> We may maintain links from our Service to third party Web sites. We do not evaluate, and we are not responsible for, the content of any such third party Web sites. Your use of any such third party Web site you visit is governed by the Terms of Use and privacy policies of such third party Web site, not by these Terms of Use.</li>
    <li><strong>TERM AND TERMINATION.</strong> The legal agreement formed by these Terms of Use will remain in effect for as long as you use the Service, except that:
    <p>You may delete your account at any time, for any reason, by email to us at <a href="mailto:unsubscribe@engagenie.com">unsubscribe@engagenie.com</a>, in which case these Terms of Use will automatically terminate.</p>
    <p>We may stop making the Service available to you at any time, for any reason, in which case these Terms of Use will automatically terminate.</p>
    <p>If these Terms of Use terminate, the following sections will survive such termination in full force and effect: 2, 3, 5, 6, and 8 through 16.</p></li>
    <li><strong>DISCLAIMER OF WARRANTIES.</strong> WE PROVIDE THE SERVICE (AND ANY CONTENT, FEATURES, APPLICATIONS, OR PRODUCTS OFFERED OR MADE AVAILABLE THROUGH THE SERVICE) “AS IS”. WE DO NOT MAKE ANY WARRANTIES OF ANY KIND WITH RESPECT TO THE SERVICE, NOR DO WE GUARANTEE THAT THE SERVICE WILL BE CONTINUOUSLY AVAILABLE OR SECURE. WE DISCLAIM ALL EXPRESS AND IMPLIED WARRANTIES WITH RESPECT TO THE SERVICE, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT. Certain state laws do not allow limitations on implied warranties; if those laws apply to you, some or all of the disclaimers above may not apply to you, and you may have additional rights.</li>
    <li>LIMITATION OF LIABILITY. WE WILL NOT BE LIABLE TO YOU FOR ANY LOST PROFITS OR FOR ANY INCIDENTAL, INDIRECT, SPECIAL OR CONSEQUENTIAL DAMAGES, REGARDLESS OF THE CAUSE OF ACTION AND EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. OUR TOTAL LIABILITY TO YOU FOR ANY CLAIM ARISING UNDER THIS AGREEMENT WILL NOT EXCEED $100 (OR, IF GREATER THAN $100, THE AMOUNT OF FEES YOU HAVE PAID TO US FOR THE SERVICE DURING THE 12 MONTH PERIOD PRECEDING THE APPLICABLE CLAIM). Certain state laws may not allow the exclusion of liability for incidental or consequential damages, so the above limitation may not apply to you, and you may have additional rights.</li>
    <li><strong>INDEMNIFICATION.</strong> You agree to defend, indemnify and hold us harmless from and against any claims, actions, causes of action, or proceedings brought by a third party, and all resulting damages, costs (including reasonable attorney’s fees), expenses, penalties and other liability, that arise out of Your Content or your breach of these Terms of Use.</li>
    <li><strong>GOVERNING LAW; DISPUTES.</strong>These Terms of Use are governed by the laws of the State of Delaware, without regard to its conflict of laws rules. The exclusive venue for any action or dispute arising out of these Terms of Use will be the courts located in the State of Delaware, and you hereby submit to the personal jurisdiction of those courts.</li>
    <li><strong>MISCELLANEOUS.</strong>These Terms of Use form the entire agreement between you and us with respect to the use of the Service. It supersedes any prior or contemporaneous agreements or communications between us. If we fail to enforce any term of these Terms of Use, it will not be considered a waiver. Any amendment to these Terms of Use must be made in a writing signed by us or made in accordance with Section 1 of these Terms of Use. All of our rights under these Terms of Use are freely assignable by us, including in connection with a merger, acquisition, sale of assets, or by operation of law. These Terms of Use do not confer any right on any third party.</li>
</ol>
</div>
</body>
</html>